### ISSUE TITLE
Service not working

### ISSUE THREAD

**Issue by lgblkb** [DocTAG/doctag-core#2]
Hi! I'm facing deployment issues. 

Steps taken:
1. Followed deployment instructions using `docker-compose.yaml` file.
2. Changed project requirements: replaced `sklearn` with `scikit-learn`.

This resulted in:
1. When accessing the web interface and providing `Test` for both username and password, the webserver is stuck indefinitely:
 
![image](https://user-images.githubusercontent.com/9667983/217716364-448fab2e-be4a-4f23-a970-83de24af61e1.png)

2. The logs in web service container:
![image](https://user-images.githubusercontent.com/9667983/217716521-1bcdf547-35df-4f49-8685-1b40e862f5f9.png)

What might be the problem? Any way to fix this?

**Comment by OrnellaIrrera** [comment]
Dear Dias, 

Thank you for your question. Another member had a similar problem. A solution could be the following:

1) Download the repo again (I pushed some modifications, hence you need to download the updates)
2) Open DocTAG_Dockerized/baseurl.txt file and put the baseURL of the server where DocTAG is deployed. If the server hosting DocTAG has the baseURL http://example.com/server/example/, specify this URL in place of the http://0.0.0.0:8000/ provided by default. 
3) remove the already existing image of DocTAG (if any)
4) run docker-compose up and wait until the installation process is finished

Please, let me know if you need further information.

Ornella

**Comment by lgblkb** [comment]
Thanks! Now it works!
